version: '3.8'

services:
  eureka-server:
    image: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - my_network
    environment:
      - spring.application.name=eureka-server
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
      - eureka.server.enable-self-preservation=false

  # API Gateway
  api-gateway:
    image: api-gateway
    container_name: api-gateway
    ports:
      - "9090:9090"
    networks:
      - my_network
    environment:
      - spring.application.name=api-gateway
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  # MySQL Database
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cafe_users
    ports:
      - "3307:3306"
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql





  # Order Service
  user-service:
    image: user-service
    depends_on:
      - eureka-server
      - mysql-db
    container_name: user-service
    ports:
      - "8081:8081"
    networks:
      - my_network
    environment:

      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/cafe_users
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root



  product-service:
    image: product-service
    container_name: product-service
    ports:
      - "8082:8082"
    networks:
      - my_network
    environment:

      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/cafe_users
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    depends_on:
      - eureka-server
      - mysql-db

  order-service:
    image: order-service
    depends_on:
      - eureka-server
      - mysql-db
    container_name: order-service
    ports:
      - "8083:8083"
    networks:
      - my_network
    environment:

      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/cafe_users
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root




  payment-service:
    image: payment-service
    container_name: payment-service
    ports:
      - "8084:8084"
    networks:
      - my_network
    environment:

      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/cafe_users
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    depends_on:
      - eureka-server
      - mysql-db

networks:
  my_network:
    driver: bridge
volumes:
  mysql_data:
    driver: local